### ISSUE TITLE
Missing some images

### ISSUE THREAD

**Issue by stek29** [TelegramTW/unofficial-landing-site#2]
`blog_side_image`'s are missing.
Also, there's no way to tell if some image is meant to be cover or not.

**Comment by Haraguroicha** [comment]
Unfortunately, those images are must to be missing in the article, because I have not reserve an attribute to store image URL.

**Comment by stek29** [comment]
@Haraguroicha Would you accept a PR resolving this issue?

**Comment by Haraguroicha** [comment]
Sorry for late response, and welcome for any PR.
